baseURL: /
languageCode: en-us
build:
  writeStats: true
title: Matthew Stanley Engineer
# Uncomment below to use aafu as hugo theme. See instructions in README.md
# theme: aafu

params:
  author: Matthew Stanley
  description: Matthew Stanley Engineer
  copyright: powered by [hugo](https://gohugo.io/)
  theme:
    mainTheme: dark
    showAttribute: true
    singlePage: false
  accordion:
    - item: about_me
      expand: true # only the first `expand: true` will take effect
    - item: skills
      panel_id: skill-panel
    - item: education
    - item: experiences
    - item: publications
    - item: certification
    - item: teaching
    - item: projects
    - item: hobbies
